spring:
  datasource:
    url: jdbc:h2:mem:test_db\;MODE=PostgreSQL\;INIT=CREATE SCHEMA IF NOT EXISTS test_db\;RUNSCRIPT FROM 'classpath:migration/LoadData.sql'\;
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 5000
