spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

flyway:
  url: jdbc:h2:mem:testdb
  user: sa
  password:
  locations: classpath:db/migration
  enabled: true

server:
  port: 5000
